### ISSUE TITLE
VPS 网速测试脚本 - testspeed | 南琴浪博客

### ISSUE THREAD

**Issue by nanqinlang** [nanqinlang/sometimesnaive.org#60]
https://sometimesnaive.org/article/linux/bash/testspeed

**Comment by nanqinlang** [comment]
`来测试下留言区有木有毛病`

**Comment by Aniverse** [comment]
我好像在博客那边留言不了……

ERROR: No matched servers: 5674
[Error] 南宁联通 测试失败，可能是此节点现不可用
ERROR: No matched servers: 4589
[Error] 北京电信 测试失败，可能是此节点现不可用
ERROR: No matched servers: 5122
[Error] 无锡移动 测试失败，可能是此节点现不可用

还有一个延迟是这样子的
北京联通      7.34 Mbit/s       0.00 Mbit/s         1800000.0 ms

我觉得节点不可用的话排版可以考虑改成这样子的，看上去整齐一点

成都移动      15.91 Mbit/s      25.44 Mbit/s        227.532 ms 
无锡移动      测试失败，可能是此节点现不可用（红色）
宁波移动      24.84 Mbit/s      54.25 Mbit/s        244.598 ms

**Comment by nanqinlang** [comment]
@Aniverse  
谢谢反馈，之后会调整。

**Comment by TemplarsCreed** [comment]
[Info] 开始 三网快速测试 ...
ISP Name      Upload Speed      Download Speed      Latency     
ERROR: No matched servers: 4589
[Error] 北京电信 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 郑州电信 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 成都电信 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 深圳电信 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 沈阳联通 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 北京联通 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 合肥联通 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
ERROR: No matched servers: 5674
[Error] 南宁联通 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 合肥移动 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 成都移动 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
ERROR: No matched servers: 5122
[Error] 无锡移动 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Error] 宁波移动 测试失败，可能是此节点现不可用
[Info] 继续测试下一节点 ...
[Info] 测试时间: 
[Info] 三网测试完成 ！

**Comment by nanqinlang** [comment]
@TemplarsCreed  
我也很想知道为什么，为么这些节点都失效这么厉害  
怒了，我要删贴啦啊啊啊啊～

**Comment by TemplarsCreed** [comment]
@nanqinlang
(=_=)这就非常的尴尬了

**Comment by Aniverse** [comment]
其实应该说只要speedtest没跑完的话就会提示“测试失败，可能是此节点现不可用”，而不一定是这个节点真的不能用
我第一次来报错前用的一个192M OVZ VPS，我自己下了 speedtest.py，跑着跑着就killed了，用你的脚本也全都是“测试失败，可能是此节点现不可用”。我当时就想应该只是 Speedtest 没跑成功
后来我upgrade到512M RAM就能跑了，然后那几个节点倒是确实不能用了

TemplarsCreed 贴出的log其实也就是5122/5674/4589这三个节点不能用，这方面和我的报错一样。我估计也是 speedtest 跑到一半没跑完就被killed了之类的情况，而那三个节点是在 speedtest.py --server $1 的时候就提示找不到节点，而不是“测试失败，可能是此节点现不可用”

**Comment by nanqinlang** [comment]
@Aniverse  
依旧是比较奇怪，`speedtest.py` 并不是什么很需要内存的玩意啊。

**Comment by Aniverse** [comment]
我也挺奇怪的……没听说过谁的小内存VPS上那些bench脚本就跑不起来
FYI，我当时killed的VPS是WootHosting 5刀年付的
