### ISSUE TITLE
iptables 将 Cloudflare's IP 加入白名单 | 南琴浪博客

### ISSUE THREAD

**Issue by nanqinlang** [nanqinlang/sometimesnaive.org#78]
https://sometimesnaive.org/article/linux/technique/iptables/whitelist-cloudflare-ip

**Comment by bofei222** [comment]
开始在找qq群没有找到  发现有一个Telegram（从没接触过） 于是下载后加入@SometimesNaiveGroup 
就说了一句 第一次用Telegram
直接被T
贵群B格是真高

**Comment by nanqinlang** [comment]
@bofei222  
emmm。。。不好意思，估计是误杀了。

**Comment by bofei222** [comment]
@nanqinlang
emmm。。没关系
感谢大神回复
